<div class="main wrapper">
  <h2>Componentes</h2>
  <h4>Íconos</h4>
  <p>
    Ocupamos los íconos de Material Design, <a href="https://material.io/icons/" target="_blank">aquí</a> hay una lista de todos y cómo usarlos en el HTML.
  </p>
  <h4>Alertas</h4>
  <div class="notice notice-error">
    <span>Esto es un error, oh no :(</span>
    <button class="notice-close" data-close-parent>
      <i class="material-icons">&#xE5CD;</i>
    </button>
  </div>
  <div class="notice notice-warning">
    <span>Algo anda mal, pero no te preocupes demasiado :)</span>
    <button class="notice-close" data-close-parent>
      <i class="material-icons">&#xE5CD;</i>
    </button>
  </div>
  <div class="notice notice-success">
    <span>Todo está perfecto :D</span>
    <button class="notice-close" data-close-parent>
      <i class="material-icons">&#xE5CD;</i>
    </button>
  </div>
</div>