<div class="list-view-layout-main-wrapper wrapper">
  <div class="list-view-layout smallest-container">
    <div class="head-flex">
      <a href="/users/" class="btn--icon">
        <i class="material-icons">&#xE5C4;</i>
      </a>
      <h2 class="border-title flex-1">Nuevo Usuario</h2>
    </div>
    <div class="card padbox-1">
      <form action="/users/" class="form">
        <div class="form-row">
          <div class="flexbox">
            <label class="flex-2 sright">
              <span class="form-label">Nombre</span>
              <input type="text" class="form-input">
            </label>
            <label class="flex-1 sright">
              <span class="form-label">Apellido Paterno</span>
              <input type="text" class="form-input">
            </label>
            <label class="flex-1">
              <span class="form-label">Apellido Materno</span>
              <input type="text" class="form-input">
            </label>
          </div>
        </div>
        <div class="form-row txt-right">
          <button type="submit" class="btn--primary">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>