<div class="list-view-layout-main-wrapper wrapper">
  <div class="list-view-layout">
    <div class="head-flex">
      <h2 class="border-title flex-1">Formularios</h2>
      <div>
        <button class="btn--secondary sright">Crear Pregunta</button>
        <a href="/forms/new" class="btn--primary">Crear Formulario</a>
      </div>
    </div>
    <div class="aside-content-container">
      <aside class="aside" data-sticker='{ "offset": 76, "bottom": 16 }'>
        <div class="relative fullh">
          <form action="#" class="form list-header">          
            <div class="input-w-btn">
              <input type="text" name="query" class="form-input" placeholder="Filtrar...">
              <button type="submit" class="btn--icon-in-input" tabindex="-1">
                <i class="material-icons">&#xE8B6;</i>
              </button>
            </div>
          </form>
          <div class="scrollable list-content card padbox-1">
            <a href="" class="list-item">
              <span class="item-title flex-1" title="Formulario Alfa">Formulario Alfa Falfa</span>
              <div class="flexbox">
                <div class="flex-1">
                  <div class="mini-row txt-active">General Hospital</div>
                  <div class="mini-row">Vicodin</div>
                </div>
                <button class="btn--icon" title="Editar">
                  <i class="material-icons">&#xE254;</i>
                </button>
                <button class="btn--icon" title="Estadísticas">
                  <i class="material-icons">&#xE24B;</i>
                </button>
              </div>
              <div class="flexbox txt-light txt-smaller">
                <div class="flex-1">Dr. Strange</div>
                <div>20 nov 2015</div>
              </div>
            </a>
            <div class="list-item">
              <span class="item-title flex-1" title="Formulario Alfa">Formulario Alfa Falfa</span>
              <div class="flexbox">
                <div class="flex-1">
                  <div class="mini-row txt-active">General Hospital</div>
                  <div class="mini-row">Vicodin</div>
                </div>
                <button class="btn--icon" title="Editar">
                  <i class="material-icons">&#xE254;</i>
                </button>
                <button class="btn--icon" title="Estadísticas">
                  <i class="material-icons">&#xE24B;</i>
                </button>
              </div>
              <div class="flexbox txt-light txt-smaller">
                <div class="flex-1">Dr. Strange</div>
                <div>20 nov 2015</div>
              </div>
            </div>
            <div class="list-item">
              <span class="item-title flex-1" title="Formulario Alfa">Formulario Alfa</span>
              <div class="flexbox">
                <div class="flex-1">
                  <div class="mini-row txt-active">General Hospital</div>
                  <div class="mini-row">Vicodin</div>
                </div>
                <button class="btn--icon" title="Editar">
                  <i class="material-icons">&#xE254;</i>
                </button>
                <button class="btn--icon" title="Estadísticas">
                  <i class="material-icons">&#xE24B;</i>
                </button>
              </div>
              <div class="flexbox txt-light txt-smaller">
                <div class="flex-1">Dr. Strange</div>
                <div>20 nov 2015</div>
              </div>
            </div>
            <div class="list-item">
              <span class="item-title flex-1" title="Formulario Lorem Ipsum Dolor Sit Amet">
                Formulario Lorem Ipsum Dolor Sit Amet
              </span>
              <div class="flexbox">
                <div class="flex-1">
                  <div class="mini-row txt-active">General Hospital</div>
                  <div class="mini-row">Vicodin</div>
                </div>
                <button class="btn--icon" title="Editar">
                  <i class="material-icons">&#xE254;</i>
                </button>
                <button class="btn--icon" title="Estadísticas">
                  <i class="material-icons">&#xE24B;</i>
                </button>
              </div>
              <div class="flexbox txt-light txt-smaller">
                <div class="flex-1">Dr. Strange</div>
                <div>20 nov 2015</div>
              </div>
            </div>
          </div>
        </div>
      </aside>
      <main class="content card padbox-1">
        <div class="flexbox">
          <div class="flex-1">
            <h3 class="marginless">Formulario Alfa Falfa</h3>
          </div>
          <div>
            <div class="dropdown-container" data-dd>
              <div class="btn--icon" data-dd-opener>
                <i class="material-icons">&#xE2C4;</i>
              </div>
              <ul class="dropdown-list">
                <li class="dropdown-list-item" data-dd-option>
                  PDF
                </li>
                <li class="dropdown-list-item" data-dd-option>
                  XLS
                </li>
              </ul>
            </div>
          </div>
          <div>            
            <a href="/forms" class="btn--icon">
              <i class="material-icons">&#xE5CD;</i>
            </a>
          </div>
        </div>
        <hr class="y-separator">
        <div class="patients-pie-chart-container sdown">
          <canvas id="patients-chart" class="patients-pie-chart"></canvas>
        </div>
        <div class="clearfix">
          <div class="float-col col-30 gender-pie-chart-container">
            <canvas id="pie-chart" class="gender-pie-chart"></canvas>
          </div>
          <div class="float-col col-70 age-pie-chart-container">
            <canvas id="age-chart" class="gender-pie-chart"></canvas>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>