<div class="list-view-layout-main-wrapper wrapper">
  <div class="list-view-layout smallest-container">
    <div class="head-flex">
      <a href="/forms/" class="btn--icon">
        <i class="material-icons">&#xE5C4;</i>
      </a>
      <h2 class="border-title flex-1">Nueva Pregunta</h2>
    </div>
    <div class="card padbox-1">
      <form action="/forms/" class="form">
        <div class="form-row">
          <label>
            <span class="form-label">Tipo</span>
            <select id="quest-type" name="type" class="form-select">
              <option value="number">Número</option>
              <option value="muliple" data-options="true">Opción Múltiple</option>
              <option value="scale" data-options="true">Escala Linear</option>
              <option value="yes-no">Si/No</option>
            </select>
          </label>
        </div>
        <div class="form-row">
          <label>
            <span class="form-label">Pregunta</span>
            <input type="text" class="form-input">
          </label>
        </div>
        <div id="quest-options-cont" class="form-row">
          <div class="form-label">Opciones</div>
          <div class="question-options" data-adder>
            <div id="question-options" data-adder-list>
              <div class="quest-option" data-adder-sample>
                <div class="flexbox">
                  <div class="drag-handle material-icons sright">
                    &#xE25D;
                  </div>
                  <div class="sright">
                    <input type="text" class="form-input" placeholder="Valor">
                  </div>
                  <div class="flex-1">
                    <input type="text" class="form-input" placeholder="Opción">
                  </div>
                </div>
              </div>
            </div>
            <div class="txt-center">
              <button type="button" class="btn--icon" data-adder-button>
                <i class="material-icons">&#xE147;</i>
              </button>
            </div>
          </div>
        </div>
        <div class="form-row txt-center">
          <button type="submit" class="btn--primary">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>