<?php

  $number_json = '{
    "id": 1,
    "type": "number",
    "question": "¿Cuántos años tiene?"
  }';

  $multiple_json = '{
    "id": 2,
    "type": "multiple",
    "question": "¿Qué mejoras ha presentado con el tratamiento?",
    "options": [
      "Ninguna",
      "Me siento mejor",
      "Me salió otro brazo",
      "Soy más guapo"
    ]
  }';

  $radio_json = '{
    "id": 2,
    "type": "radio",
    "question": "¿Qué describiría mejor su estado?",
    "options": [
      "Ninguna",
      "Renacido",
      "Destrozado",
      "En la calle de la amargura"
    ]
  }';

  $select_json = '{
    "id": 2,
    "type": "select",
    "question": "Seleccione una opción",
    "options": [
      "No quiero",
      "Está bien",
      "Mejor esta"
    ]
  }';

  $scale_json = '{
    "id": 3,
    "type": "scale",
    "question": "En una escala de 1 a 5, ¿Cómo se siente con el medicamento?",
    "options": [
      "Muy mal",
      "Mal",
      "Igual",
      "Mejor",
      "Mucho mejor"
    ]
  }';

  $yes_no_json = '{
    "id": 4,
    "type": "yes-no",
    "question": "¿Has tenido algún malestar después de tomar el medicamento?",
    "options": [
      "Si",
      "No"
    ]
  }';

  $osdi_json = '{
    "id": 1,
    "type": "osdi",
    "question": "Prueba OSDI"
  }';

?>

<div class="list-view-layout-main-wrapper wrapper">
  <div class="list-view-layout">
    <div class="head-flex">
      <a href="/forms" class="btn--icon">
        <i class="material-icons">&#xE5C4;</i>
      </a>
      <h2 class="border-title flex-1">Nuevo Formulario</h2>
      <div class="flexbox">
        <button type="submit" class="btn--primary with-icon" form="formulary-form">
          <span>Guardar</span>
          <i class="material-icons">&#xE161;</i>
        </button>
      </div>
    </div>
    <div class="aside-content-container">
      <aside class="aside" data-sticker='{ "offset": 76, "bottom": 16 }'>
        <div id="form-save" action="/forms" class="relative fullh" data-tabule>
          <div class="aside-block-header tab-triggers">
            <button class="tab-trigger" data-tabule-trigger>
              <i class="material-icons vam">&#xE8D2;</i>
              <span class="vam">Datos</span>
            </button>
            <button class="tab-trigger" data-tabule-trigger>
              <i class="material-icons vam">&#xE8AF;</i>
              <span class="vam">Preguntas</span>
            </button>
            <button class="tab-trigger" data-tabule-trigger>
              <i class="material-icons vam">&#xE3AE;</i>
              <span class="vam">Estilo</span>
            </button>
          </div>
          <div class="card scrollable aside-tabs">
            <div class="tab-container tab-container-full">
              <div class="tabs">
                <div class="tab" data-tabule-tab><!-- Datos Generales -->
                  <form id="formulary-form" action="/forms">
                    <input id="form-data" type="hidden" name="form-data">
                    <div class="form-row">
                      <label>
                        <span class="form-label">Nombre del formulario</span>
                        <input type="text" class="form-input" data-synced-input="af-title" placeholder="Nombre del formulario">
                      </label>
                    </div>
                    <div class="form-row">
                      <div data-image-input class="image-input clean">
                        <input id="med-logo-in" type="file" class="hidden-file-input">
                        <span class="form-label">Logo Medicamento</span>
                        <div class="image-placeholder">
                          <img class="image">
                          <div class="actions">
                            <div>
                              <button type="button" class="btn--icon--white" data-proxy-click="#med-logo-in">
                                <i class="material-icons">&#xE3F4;</i>
                              </button>
                              <button type="button" class="btn--icon--white" data-unset="#med-logo-in">
                                <i class="material-icons">&#xE872;</i>
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="form-row">
                      <label>
                        <span class="form-label">Nombre del formulario</span>
                        <input type="text" class="form-input">
                      </label>
                    </div>
                    <div class="form-row">
                      <label>
                        <span class="form-label">Nombre del formulario</span>
                        <input type="text" class="form-input">
                      </label>
                    </div>
                  </form>
                </div>
                <div class="tab questions-tab" data-tabule-tab>
                  <div class="questions-tab-header">
                    <form action="#" class="form list-header">          
                      <div class="input-w-btn">
                        <input type="text" name="query" class="form-input" placeholder="Filtrar...">
                        <button type="submit" class="btn--icon-in-input" tabindex="-1">
                          <i class="material-icons">&#xE8B6;</i>
                        </button>
                      </div>
                    </form>
                  </div>
                  <div id="questions-source" class="questions-list">
                    <div class="questions-list-item js-source" title="Número" data-id="1" data-question-definition="<?= htmlspecialchars($number_json) ?>">
                      <i class="material-icons" title="Número">&#xE400;</i>
                      <span class="question">¿Cuántos años tiene?</span>
                    </div>
                    <div class="questions-list-item js-source" title="Selección" data-id="1" data-question-definition="<?= htmlspecialchars($select_json) ?>">
                      <i class="material-icons" title="Selección">arrow_drop_down_circle</i>
                      <span class="question">Seleccione una opción</span>
                    </div>
                    <div class="questions-list-item js-source" title="Opción Múltiple" data-id="2" data-question-definition="<?= htmlspecialchars($multiple_json) ?>">
                      <i class="material-icons">check_box</i>
                      <span class="question">¿Qué mejoras ha presentado con el tratamiento?</span>
                    </div>
                    <div class="questions-list-item js-source" title="Opciones" data-id="6" data-question-definition="<?= htmlspecialchars($radio_json) ?>">
                      <i class="material-icons">radio_button_checked</i>
                      <span class="question">¿Qué describiría mejor su estado?</span>
                    </div>
                    <div class="questions-list-item js-source" title="Escala Lineal" data-id="3" data-question-definition="<?= htmlspecialchars($scale_json) ?>">
                      <i class="material-icons">&#xE260;</i>
                      <span class="question">En una escala de 1 a 5, ¿cómo se siente con el medicamento?</span>
                    </div>
                    <div class="questions-list-item js-source" title="Si/No" data-id="4" data-question-definition="<?= htmlspecialchars($yes_no_json) ?>">
                      <i class="material-icons">&#xE3F1;</i>
                      <span class="question">¿Has tenido algún malestar después de tomar el medicamento?</span>
                    </div>
                    <div class="questions-list-item js-source" title="OSDI" data-id="5" data-question-definition="<?= htmlspecialchars($osdi_json) ?>">
                      <i class="material-icons">&#xE417;</i>
                      <span class="question">Prueba OSDI</span>
                    </div>
                  </div>
                </div>
                <div class="tab" data-tabule-tab>
                  <div class="form-row">
                    <label>
                      <span class="flexbox">
                        <span class="form-label flex-1">Color de fondo</span>
                        <input id="af-bg-color" class="jscolor color-input-impostor" value="#FFFFFF" data-appform-style-trigger>
                        <!-- <input id="af-bg-color" name="bg-color" type="color" class="color-input-hidden" value="#FFFFFF" data-input data-appform-style-trigger> -->
                      </span>
                    </label>
                  </div>
                  <div class="form-row">
                    <label><!-- <label data-input-color> -->
                      <span class="flexbox">
                        <span class="form-label flex-1">Color de realce</span>
                        <input id="af-accent-color" class="jscolor color-input-impostor" value="#397CEB" data-appform-style-trigger>
                        <!-- <input id="af-accent-color" name="accent-color" type="color" class="color-input-hidden" value="#397CEB" data-input data-appform-style-trigger> -->
                        <!-- <span class="color-input-impostor" data-impostor></span> -->
                      </span>
                    </label>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </aside>
      <main class="content card appform-outer">
        <div id="af-container" class="af-container">
          <div class="appform-wrapper">
            <header class="af-header">
              <div id="af-logos" class="af-logos">
                <img src="/assets/img/logo-thea.png" alt="">
                <img src="/assets/img/logo-hospital.png" alt="">
              </div>
              <hr class="af-separator">
              <h2 id="af-title" class="af-title clean">Nombre del formulario</h2>
            </header>
            <div class="visit-block-container">
              <div class="visit-block-legend">Visita 1</div>
              <div id="visit-block-1" class="visit-block" data-block-name="visit1"></div>
            </div>
            <div class="visit-block-container">
              <div class="visit-block-legend">Visita 2</div>
              <div id="visit-block-2" class="visit-block" data-block-name="visit2"></div>
            </div>
            <div class="visit-block-container">
              <div class="visit-block-legend">Visita 3</div>
              <div id="visit-block-3" class="visit-block" data-block-name="visit3"></div>
            </div>
            <div class="visit-block-container">
              <div class="visit-block-legend">Visita 4</div>
              <div id="visit-block-4" class="visit-block" data-block-name="visit4"></div>
            </div>
            <div class="visit-block-container">
              <div class="visit-block-legend">Bloque por defecto</div>
              <div class="visit-block dirty">
                <div class="appform-row">
                  <div class="relative">
                    <label>
                      <span class="af-label">Añade tus comentarios</span>
                      <textarea class="af-textarea" placeholder="Escribe aquí tus comentarios..."></textarea>
                    </label>
                    <div class="drag-handle">
                      <i class="material-icons">&#xE25D;</i>
                    </div>
                  </div>
                </div>
                <div class="appform-row txt-center">
                  <button type="submit" class="af-submit">
                    Terminar
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
</div>
<?= '<script id="number-quest-tmpl" type="x-tmpl-mustache">' ?>
  <div class="appform-row" data-id="<% id %>" data-question-definition="<% definition %>">
    <input type="hidden" name="<% visit_block %>[]" value="<% id %>">
    <div class="relative">
      <label>
        <span class="af-label"><% question %></span>
        <input type="number" class="af-input" name="<% id %>">
      </label>
      <div class="drag-handle material-icons">
        &#xE25D;
      </div>
    </div>
  </div>
<?= '</script>' ?>
<?= '<script id="select-quest-tmpl" type="x-tmpl-mustache">' ?>
  <div class="appform-row" data-id="<% id %>" data-question-definition="<% definition %>">
    <input type="hidden" name="<% visit_block %>[]" value="<% id %>">
    <div class="relative">
      <label>
        <span class="af-label"><% question %></span>
        <select class="af-select"> name="<% id %>">
          <%# options %>
            <option value="<% . %>"><% . %></option>
          <%/ options %>
        </select>
      </label>
      <div class="drag-handle material-icons">
        &#xE25D;
      </div>
    </div>
  </div>
<?= '</script>' ?>
<?= '<script id="multiple-quest-tmpl" type="x-tmpl-mustache">' ?>
  <div class="appform-row" data-id="<% id %>" data-question-definition="<% definition %>">
    <input type="hidden" name="<% visit_block %>[]" value="<% id %>">
    <div class="relative">
      <span class="af-label"><% question %></span>
      <div class="af-checkbox">
        <%# options %>
          <label>
            <input type="checkbox" name="<% id %>" value="<% . %>">
            <span class="af-checkbox-impostor">
              <i class="material-icons">&#xE5CA;</i>
            </span>
            <span class="af-list-label"><% . %></span>
          </label>
        <%/ options %>
      </div>
      <div class="drag-handle material-icons">
        &#xE25D;
      </div>
    </div>
  </div>
<?= '</script>' ?>
<?= '<script id="scale-quest-tmpl" type="x-tmpl-mustache">' ?>
  <div class="appform-row" data-id="<% id %>" data-question-definition="<% definition %>">
    <input type="hidden" name="<% visit_block %>[]" value="<% id %>">
    <div class="relative">
      <span class="af-label"><% question %></span>
      <div class="af-radio af-scale">
        <%# options %>
          <label>
            <input type="radio" name="<% id %>" value="<% . %>">
            <span class="af-radio-active"></span>
            <span class="af-radio-label"><% . %></span>
          </label>
        <%/ options %>
      </div>
      <div class="drag-handle material-icons">
        &#xE25D;
      </div>
    </div>
  </div>
<?= '</script>' ?>
<?= '<script id="yes-no-quest-tmpl" type="x-tmpl-mustache">' ?>
  <div class="appform-row" data-id="<% id %>" data-question-definition="<% definition %>">
    <input type="hidden" name="<% visit_block %>[]" value="<% id %>">
    <div class="relative">
      <span class="af-label"><% question %></span>
      <div class="af-radio">
        <%# options %>
          <label>
            <input type="radio" name="<% id %>" value="<% . %>">
            <span class="af-radio-active"></span>
            <span class="af-radio-label"><% . %></span>
          </label>
        <%/ options %>
      </div>
      <div class="drag-handle material-icons">
        &#xE25D;
      </div>
    </div>
  </div>
<?= '</script>' ?>
<?= '<script id="radio-quest-tmpl" type="x-tmpl-mustache">' ?>
  <div class="appform-row" data-id="<% id %>" data-question-definition="<% definition %>">
    <input type="hidden" name="<% visit_block %>[]" value="<% id %>">
    <div class="relative">
      <span class="af-label"><% question %></span>
      <div class="af-options">
        <%# options %>
          <label>
            <input type="radio" name="<% id %>" value="<% . %>">
            <span class="af-options-impostor">
              <span class="ball"></span>
            </span>
            <span class="af-list-label"><% . %></span>
          </label>
        <%/ options %>
      </div>
      <div class="drag-handle material-icons">
        &#xE25D;
      </div>
    </div>
  </div>
<?= '</script>' ?>
<?= '<script id="osdi-quest-tmpl" type="x-tmpl-mustache">' ?>
  <div class="appform-row" data-id="<% id %>" data-question-definition="<% definition %>">
    <input type="hidden" name="<% visit_block %>[]" value="<% id %>">
    <div class="relative">
      <label>
        <span class="af-label"><% question %></span>
        <span class="input-with-button">
          <input type="number" class="af-input" name="<% id %>">
          <button type="button" class="af-button">Tomar prueba</button>
        </span>
      </label>
      <div class="drag-handle material-icons">
        &#xE25D;
      </div>
    </div>
  </div>
<?= '</script>' ?>
<?= '<script id="styles-quest-tmpl" type="x-tmpl-mustache">' ?>
  .appform-row.gu-mirror {
    background-color: <% bg %>;
    box-shadow: 0 0 0 2rem <% bg %>;
  }
  .af-container {
    background-color: <% bg %>;
    color: <% text %>;
  }
  .af-label {
    color: <% accent %>;
  }
  .af-input, .af-textarea {
    background-color: <% input_bg %>;
    box-shadow: 0 0 0 1px <% bg %>, 0 0 0 0px <% accent %>;
  }
  .af-input:focus, .af-textarea:focus {
    box-shadow: 0 0 0 1px <% bg %>, 0 0 0 5px <% accent %>;
  }
  .af-submit, .af-button {
    background-color: <% accent %>;
    color: <% accent_text %>;
  }
  .af-submit:hover, .af-submit:focus, .af-button:hover, .af-button:focus {
    background-color: <% accent_darken %>;
  }
  .af-checkbox input[type=checkbox]:checked + .af-checkbox-impostor {
    background-color: <% accent %>;
  }
  .af-checkbox-impostor, .af-options-impostor {
    background-color: <% input_bg %>;
    color: <% accent_text %>;
  }
  .af-radio label {
    background-color: <% input_bg %>;
  }
  .af-radio label:after {
    color: <% text %>;
  }
  .af-radio-active {
    background-color: <% accent %>;
  }
  .af-radio input[type=radio]:checked + .af-radio-active + .af-radio-label {
    color: <% accent_text %>;
  }
<?= '</script>' ?>







